on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  BRANCH: runs/${{ github.run_number }}.${{ github.run_attempt }}

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: release
      cancel-in-progress: false
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      # init node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      # build/release to a run branch
      - name: Checkout ${{ env.BRANCH }}
        run: git checkout -b $BRANCH
      - run: npm ci
      - run: npm build
      - run: npm test
      # publish the npm package
      - name: Publish package
        run: .github/scripts/publish-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
